### PR TITLE
practical-porcupines

### PR DESCRIPTION
**Pull request by Owez**
API measuring GMSL with an ecosystem of a discord bot and webportal built around it, all contained nicely in 1 repository

### CODE REVIEW

**Comment by Owez** [comment]
Final push of day done

**Comment by Owez** [comment]
Some dev notes: https://github.com/scOwez/code-jam-5/tree/master/practical_porcupines#development-notes

**Comment by Owez** [comment]
End of day notes:

- Core: 10% finished
- flask_api: 0% finished (waiting on the core, will start tomorrow nonetheless)
- discord_bot: 75% finished (waiting on flask_api for testing)
- webportal: 50% finished (need to hook upto api)

**Comment by Owez** [comment]
Everything is 100% finished and got in some last minute tidying and README.md changes :sunglasses:

**Comment by Owez** [comment]
The `Pipenv` (also lockfile) and `.env` files **need** transferring to the `practical_porcupine/` folder and the `README.md` is misleading with machine learning but request to change last has been denied.

Allow edits from reviewers/maintainers is already checked.

**Comment by lemonsaurus** [comment]
Fixed some minor linting errors and problems with getting this to build. These are mostly our fault for making this too difficult, so that's to be expected. We'll avoid it next jam with a better submission system.

**Pull request merged**
